version: '3'

services:
  mysql:
    image: mysql:5.7
    restart: always
    volumes:
      - ./mysql-data:/var/lib/mysql
      - ./dump:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_DATABASE: "echo"
      MYSQL_USER: "echouser"
      MYSQL_PASSWORD: "echopwd"
  webservice:
    build: .
    volumes:
      - ./mobilerestkit:/go/src/github.com/alamyudi/echo-app/mobilerestkit
      - ./echokit:/go/src/github.com/alamyudi/echo-app/echokit
    ports:
      - "8081:8081"
    links:
      - mysql:mysql
    depends_on:
      - mysql
    